---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'Update apt'
      become: yes
      raw: apt update
    - name: 'install python'
      become: yes
      raw: apt-get -y install python
    - name: Gathering facts
      setup:
  tasks:
    ####
    # Updating
    ##
    - name: Update package source lists
      become: yes
      apt:
        update_cache: yes
    - name: Upgrade the system packages and kernel
      become: yes
      apt:
        upgrade: dist